AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - 'bin/*'
    - '*.gemspec'
    - 'migrations/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/support/**/*.rb'
    - 'spec/factories.rb'
    - 'scripts/benchmark.rb'

Style/FileName:
  Exclude:
    - '**/Rakefile'
    - '**/Gemfile'
